table dim_month
	lineageTag: e1ccc966-f36d-5023-b6fa-fe3f925b6f15

	column month
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d6708244-0318-57b7-ae70-0bb7763fe2cc
		summarizeBy: none
		sourceColumn: month

	column month_index
		dataType: int64
		formatString: 0
		lineageTag: 8fcb38eb-b13c-5109-8f1e-7aeac48d91c3
		summarizeBy: none
		sourceColumn: month_index

	column year
		dataType: int64
		formatString: 0
		lineageTag: a620a00c-764f-53ef-a9dd-a1e85d8999f3
		summarizeBy: sum
		sourceColumn: year

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: 0e286780-3962-5889-b8b2-3edb5320c73a
		summarizeBy: sum
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: 2a28cac1-de5e-5da5-acc7-e5c4b7f5bc10
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

	column month_label
		dataType: string
		lineageTag: b282a913-b390-5ddd-95eb-ddc959746ed8
		summarizeBy: none
		sourceColumn: month_label
		sortByColumn: month_index

	column quarter
		dataType: string
		lineageTag: b60d01bb-c085-52d6-81a3-82ba122e2ecd
		summarizeBy: none
		sourceColumn: quarter

	partition dim_month = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\tables\dim_month.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type date}, {"month_index", Int64.Type}, {"year", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"month_label", type text}, {"quarter", type text}})
				in
				    Typed
